import Interpreter from "js-interpreter";
import initSimulator from "./init";

/**
 * Runs the simulator program in js-interpreter. Each tick runs steps for a
 * few milliseconds and then pauses for a while, so the page stays responsive
 * even for programs without delay. While the program waits in delay(), no
 * ticks are scheduled at all: delay() wakes the runtime up again through
 * interpreter.onResume.
 *
 * The interpreter lives here and not in the Redux store, because it is
 * neither serializable nor something a reducer should create or run.
 */

const STEP_BUDGET_MS = 4;
// Pause after a full tick: leaves the main thread to rendering and input.
const YIELD_MS = 100;

let current = null; // { interpreter, controller }

/**
 * Start the program. A running program is stopped first.
 * @param {string} code Program generated by the simulator generator.
 * @param {{onFinish?: function(), onError?: function(Error)}} callbacks
 */
export function startRuntime(code, { onFinish, onError } = {}) {
  stopRuntime();

  let interpreter;
  try {
    interpreter = new Interpreter(code, initSimulator);
  } catch (error) {
    // Syntax error in the generated program
    onError?.(error);
    return;
  }

  const controller = new AbortController();
  current = { interpreter, controller };

  const finish = (callback) => {
    if (current?.controller === controller) {
      current = null;
    }
    callback();
  };

  let timeout = null;
  const schedule = (delay = 0) => {
    if (controller.signal.aborted) {
      return;
    }
    window.clearTimeout(timeout);
    timeout = window.setTimeout(nextStep, delay);
  };
  controller.signal.addEventListener("abort", () =>
    window.clearTimeout(timeout),
  );
  interpreter.onResume = () => schedule();

  function nextStep() {
    if (controller.signal.aborted) {
      return;
    }
    const start = performance.now();
    try {
      do {
        if (!interpreter.step()) {
          finish(() => onFinish?.());
          return;
        }
        if (interpreter.getStatus() !== Interpreter.Status.STEP) {
          // Waiting in delay(): onResume continues the program.
          return;
        }
      } while (performance.now() - start < STEP_BUDGET_MS);
    } catch (error) {
      finish(() => onError?.(error));
      return;
    }
    schedule(YIELD_MS);
  }
  nextStep();
}

/**
 * Stop the running program and reset the simulated outputs. Also resets the
 * outputs after a program stopped by itself, e.g. because of an error.
 */
export function stopRuntime() {
  if (current) {
    current.controller.abort();
    current = null;
  }
  resetOutputs();
}

function resetOutputs() {
  // LEDs of the QOOOL fluoro bee
  for (let led = 1; led <= 4; led++) {
    const element = document.getElementById(`fluoro_led${led}`);
    if (element) {
      element.style.fill = "black";
    }
  }
  // RGB LED on the board: back to the colour of the graphic
  const rgbLed = document.getElementById("board-complex_svg__circle270");
  if (rgbLed) {
    rgbLed.style.fill = "";
  }
}
