import Interpreter from "js-interpreter";
import initSimulator from "./init";

/**
 * Runs the simulator program in js-interpreter, one step per tick, so the
 * page stays responsive even for programs without delay.
 *
 * The interpreter lives here and not in the Redux store, because it is
 * neither serializable nor something a reducer should create or run.
 */

let current = null; // { interpreter, controller }

/**
 * Start the program. A running program is stopped first.
 * @param {string} code Program generated by the simulator generator.
 * @param {{onFinish?: function(), onError?: function(Error)}} callbacks
 */
export function startRuntime(code, { onFinish, onError } = {}) {
  stopRuntime();

  let interpreter;
  try {
    interpreter = new Interpreter(code, initSimulator);
  } catch (error) {
    // Syntax error in the generated program
    onError?.(error);
    return;
  }

  const controller = new AbortController();
  current = { interpreter, controller };

  const finish = (callback) => {
    if (current?.controller === controller) {
      current = null;
    }
    callback();
  };

  const nextStep = () => {
    if (controller.signal.aborted) {
      return;
    }
    let hasMoreSteps;
    try {
      hasMoreSteps = interpreter.step();
    } catch (error) {
      finish(() => onError?.(error));
      return;
    }
    if (hasMoreSteps) {
      window.setTimeout(nextStep, 0);
    } else {
      finish(() => onFinish?.());
    }
  };
  nextStep();
}

/**
 * Stop the running program and reset the simulated outputs.
 */
export function stopRuntime() {
  if (!current) {
    return;
  }
  current.controller.abort();
  current = null;
  resetOutputs();
}

function resetOutputs() {
  // LEDs of the QOOOL fluoro bee
  for (let led = 1; led <= 4; led++) {
    const element = document.getElementById(`fluoro_led${led}`);
    if (element) {
      element.style.fill = "black";
    }
  }
}
