
export const LOOPS = {
    CONTROLS_FLOW_STATEMENTS_HELPURL: "https://de.wikipedia.org/wiki/Kontrollstruktur",
    CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK: "Die Schleife abbrechen",
    CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE: "mit der nächsten Iteration der Schleife fortfahren",
    CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK: "Die umgebende Schleife beenden.",
    CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE: "Diese Anweisung abbrechen und mit dem nächsten Schleifendurchlauf fortfahren.",
    CONTROLS_FLOW_STATEMENTS_WARNING: "Warnung: Dieser Block sollte nur in einer Schleife verwendet werden.",
    CONTROLS_FOREACH_HELPURL: "https://de.wikipedia.org/wiki/For-Schleife",
    CONTROLS_FOREACH_TITLE: "Für Wert %1 aus der Liste %2",
    CONTROLS_FOREACH_TOOLTIP: "Führe eine Anweisung für jeden Wert in der Liste aus und setzte dabei die Variable \"%1\" auf den aktuellen Listenwert.",
    CONTROLS_FOR_HELPURL: "https://de.wikipedia.org/wiki/For-Schleife",
    CONTROLS_FOR_TITLE: "Zähle %1 von %2 bis %3 mit %4",
    CONTROLS_FOR_TOOLTIP: "Zähle die Variable \"%1\" von einem Startwert bis zu einem Zielwert und führe für jeden Wert eine Anweisung aus.",

    CONTROLS_REPEAT_HELPURL: "https://de.wikipedia.org/wiki/For-Schleife",
    CONTROLS_REPEAT_INPUT_DO: "mache",
    CONTROLS_REPEAT_TITLE: "Wiederhole %1 mal",
    CONTROLS_REPEAT_TOOLTIP: "Eine Anweisung mehrfach ausführen.",
    CONTROLS_WHILEUNTIL_HELPURL: "https://de.wikipedia.org/wiki/Schleife_%28Programmierung%29",
    CONTROLS_WHILEUNTIL_OPERATOR_UNTIL: "Wiederhole bis",
    CONTROLS_WHILEUNTIL_OPERATOR_WHILE: "Wiederhole solange",
    CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL: "Führe die Anweisung solange aus wie die Bedingung falsch (false) ist.",
    CONTROLS_WHILEUNTIL_TOOLTIP_WHILE: "Führe die Anweisung solange aus wie die Bedingung wahr (true) ist.",
}