
export const MATH = {
    MATH_ADDITION_SYMBOL: "+",  // untranslated
    MATH_ARITHMETIC_HELPURL: "https://de.wikipedia.org/wiki/Grundrechenart",
    MATH_ARITHMETIC_TOOLTIP_ADD: "Ist die Summe zweier Werte.",
    MATH_ARITHMETIC_TOOLTIP_DIVIDE: "Ist der Quotient zweier Werte.",
    MATH_ARITHMETIC_TOOLTIP_MINUS: "Ist die Differenz zweier Werte.",
    MATH_ARITHMETIC_TOOLTIP_MULTIPLY: "Ist das Produkt zweier Werte.",
    MATH_ARITHMETIC_TOOLTIP_POWER: "Ist der erste Wert potenziert mit dem zweiten Wert.",
    MATH_CHANGE_HELPURL: "https://de.wikipedia.org/wiki/Inkrement_und_Dekrement",
    MATH_CHANGE_TITLE: "erhöhe %1 um %2",
    MATH_CHANGE_TOOLTIP: "Addiert einen Wert zur Variable \"%1\" hinzu.",
    MATH_CONSTANT_HELPURL: "https://de.wikipedia.org/wiki/Mathematische_Konstante",
    MATH_CONSTANT_TOOLTIP: "Mathematische Konstanten wie: π (3.141…), e (2.718…), φ (1.618…), sqrt(2) (1.414…), sqrt(½) (0.707…) oder ∞ (unendlich).",
    MATH_CONSTRAIN_HELPURL: "https://en.wikipedia.org/wiki/Clamping_%28graphics%29",  // untranslated
    MATH_CONSTRAIN_TITLE: "begrenze %1 von %2 bis %3",
    MATH_CONSTRAIN_TOOLTIP: "Begrenzt den Wertebereich auf den \"von\"-Wert bis einschließlich zum \"bis\"-Wert. (inklusiv)",
    MATH_DIVISION_SYMBOL: "÷",  // untranslated
    MATH_IS_DIVISIBLE_BY: "ist teilbar durch",
    MATH_IS_EVEN: "ist gerade",
    MATH_IS_NEGATIVE: "ist negativ",
    MATH_IS_ODD: "ist ungerade",
    MATH_IS_POSITIVE: "ist positiv",
    MATH_IS_PRIME: "ist eine Primzahl",
    MATH_IS_TOOLTIP: "Überprüft ob eine Zahl gerade, ungerade, eine Primzahl, ganzzahlig, positiv, negativ oder durch eine zweite Zahl teilbar ist.  Gibt wahr (true) oder falsch (false) zurück.",
    MATH_IS_WHOLE: "ist eine ganze Zahl",
    MATH_MODULO_HELPURL: "https://de.wikipedia.org/wiki/Modulo",
    MATH_MODULO_TITLE: "Rest von %1 ÷ %2",
    MATH_MODULO_TOOLTIP: "Der Rest nach einer Division.",
    MATH_MULTIPLICATION_SYMBOL: "×",
    MATH_NUMBER_HELPURL: "https://de.wikipedia.org/wiki/Zahl",
    MATH_NUMBER_TOOLTIP: "Eine Zahl.",
    MATH_ONLIST_HELPURL: "http://www.sysplus.ch/einstieg.php?links:menu&seite:4125&grad:Crash&prog:Excel",
    MATH_ONLIST_OPERATOR_AVERAGE: "Mittelwert einer Liste",
    MATH_ONLIST_OPERATOR_MAX: "Maximalwert einer Liste",
    MATH_ONLIST_OPERATOR_MEDIAN: "Median einer Liste",
    MATH_ONLIST_OPERATOR_MIN: "Minimalwert einer Liste",
    MATH_ONLIST_OPERATOR_MODE: "am häufigsten in Liste",
    MATH_ONLIST_OPERATOR_RANDOM: "Zufallswert einer Liste",
    MATH_ONLIST_OPERATOR_STD_DEV: "Standardabweichung einer Liste",
    MATH_ONLIST_OPERATOR_SUM: "Summe einer Liste",
    MATH_ONLIST_TOOLTIP_AVERAGE: "Ist der Durchschnittswert aller Werte in einer Liste.",
    MATH_ONLIST_TOOLTIP_MAX: "Ist der größte Wert in einer Liste.",
    MATH_ONLIST_TOOLTIP_MEDIAN: "Ist der Median aller Werte in einer Liste.",
    MATH_ONLIST_TOOLTIP_MIN: "Ist der kleinste Wert in einer Liste.",
    MATH_ONLIST_TOOLTIP_MODE: "Findet den am häufigsten vorkommenden Wert in einer Liste.  Falls kein Wert öfter vorkommt als alle anderen, wird die originale Liste zurückgeben",
    MATH_ONLIST_TOOLTIP_RANDOM: "Gebe einen zufälligen Wert aus der Liste zurück.",
    MATH_ONLIST_TOOLTIP_STD_DEV: "Ist die standardisierte Standardabweichung aller Werte in der Liste",
    MATH_ONLIST_TOOLTIP_SUM: "Ist die Summe aller Werte in einer Liste.",
    MATH_POWER_SYMBOL: "^",
    MATH_RANDOM_FLOAT_HELPURL: "https://de.wikipedia.org/wiki/Zufallszahlen",
    MATH_RANDOM_FLOAT_TITLE_RANDOM: "Zufallszahl (0.0 -1.0)",
    MATH_RANDOM_FLOAT_TOOLTIP: "Erzeuge eine Zufallszahl zwischen 0.0 (inklusiv) und 1.0 (exklusiv).",
    MATH_RANDOM_INT_HELPURL: "https://de.wikipedia.org/wiki/Zufallszahlen",
    MATH_RANDOM_INT_TITLE: "ganzzahliger Zufallswert zwischen %1 bis %2",
    MATH_RANDOM_INT_TOOLTIP: "Erzeuge einen ganzzahligen Zufallswert zwischen zwei Werten (inklusiv).",
    MATH_ROUND_HELPURL: "https://de.wikipedia.org/wiki/Runden",
    MATH_ROUND_OPERATOR_ROUND: "runden",
    MATH_ROUND_OPERATOR_ROUNDDOWN: "abrunden",
    MATH_ROUND_OPERATOR_ROUNDUP: "aufrunden",
    MATH_ROUND_TOOLTIP: "Eine Zahl auf- oder abrunden.",
    MATH_SINGLE_HELPURL: "https://de.wikipedia.org/wiki/Quadratwurzel",
    MATH_SINGLE_OP_ABSOLUTE: "Absolutwert",
    MATH_SINGLE_OP_ROOT: "Quadratwurzel",
    MATH_SINGLE_TOOLTIP_ABS: "Ist der Absolutwert eines Wertes.",
    MATH_SINGLE_TOOLTIP_EXP: "Ist Wert der Exponentialfunktion eines Wertes.",
    MATH_SINGLE_TOOLTIP_LN: "Ist der natürliche Logarithmus eines Wertes.",
    MATH_SINGLE_TOOLTIP_LOG10: "Ist der dekadische Logarithmus eines Wertes.",
    MATH_SINGLE_TOOLTIP_NEG: "Negiert einen Wert.",
    MATH_SINGLE_TOOLTIP_POW10: "Rechnet 10 hoch Eingabewert.",
    MATH_SINGLE_TOOLTIP_ROOT: "Ist die Quadratwurzel eines Wertes.",
    MATH_SUBTRACTION_SYMBOL: "-",
    MATH_TRIG_ACOS: "acos",
    MATH_TRIG_ASIN: "asin",
    MATH_TRIG_ATAN: "atan",
    MATH_TRIG_COS: "cos",
    MATH_TRIG_HELPURL: "https://de.wikipedia.org/wiki/Trigonometrie",
    MATH_TRIG_SIN: "sin",
    MATH_TRIG_TAN: "tan",
    MATH_TRIG_TOOLTIP_ACOS: "Ist der Arkuskosinus des Eingabewertes.",
    MATH_TRIG_TOOLTIP_ASIN: "Ist der Arkussinus des Eingabewertes.",
    MATH_TRIG_TOOLTIP_ATAN: "Ist der Arkustangens des Eingabewertes.",
    MATH_TRIG_TOOLTIP_COS: "Ist der Kosinus des Winkels.",
    MATH_TRIG_TOOLTIP_SIN: "Ist der Sinus des Winkels.",
    MATH_TRIG_TOOLTIP_TAN: "Ist der Tangens des Winkels.",
}