export const TEXT = {

    TEXT_APPEND_APPENDTEXT: "Text anhängen",
    TEXT_APPEND_HELPURL: "https://github.com/google/blockly/wiki/Text#text-modification",  // untranslated
    TEXT_APPEND_TO: "An",
    TEXT_APPEND_TOOLTIP: "Text an die Variable \"%1\" anhängen.",
    TEXT_CHANGECASE_HELPURL: "https://github.com/google/blockly/wiki/Text#adjusting-text-case",  // untranslated
    TEXT_CHANGECASE_OPERATOR_LOWERCASE: "umwandeln in kleinbuchstaben",
    TEXT_CHANGECASE_OPERATOR_TITLECASE: "umwandeln in Substantive",
    TEXT_CHANGECASE_OPERATOR_UPPERCASE: "umwandeln in GROSSBUCHSTABEN",
    TEXT_CHANGECASE_TOOLTIP: "Wandelt Schreibweise von Texten um, in Großbuchstaben, Kleinbuchstaben oder den ersten Buchstaben jedes Wortes groß und die anderen klein.",
    TEXT_CHARAT_FIRST: "Nehme ersten Buchstaben",
    TEXT_CHARAT_FROM_END: "Nehme #ten Buchstaben von hinten",
    TEXT_CHARAT_FROM_START: "Nehme #ten Buchstaben",
    TEXT_CHARAT_HELPURL: "http://publib.boulder.ibm.com/infocenter/lnxpcomp/v8v101/index.jsp?topic:%2Fcom.ibm.xlcpp8l.doc%2Flanguage%2Fref%2Farsubex.htm",
    TEXT_CHARAT_INPUT_INTEXT: "vom Text",
    TEXT_CHARAT_LAST: "Nehme letzten Buchstaben",
    TEXT_CHARAT_RANDOM: "Nehme zufälligen Buchstaben",
    TEXT_CHARAT_TAIL: "",
    TEXT_CHARAT_TOOLTIP: "Extrahiere einen Buchstaben von einer spezifizierten Position.",
    TEXT_CREATE_JOIN_ITEM_TOOLTIP: "Ein Element zum Text hinzufügen.",
    TEXT_CREATE_JOIN_TITLE_JOIN: "verbinden",
    TEXT_CREATE_JOIN_TOOLTIP: "Hinzufügen, entfernen und sortieren von Elementen.",
    TEXT_GET_SUBSTRING_END_FROM_END: "bis zum #ten Buchstaben von hinten",
    TEXT_GET_SUBSTRING_END_FROM_START: "bis zum #ten Buchstaben",
    TEXT_GET_SUBSTRING_END_LAST: "bis zum letzten Buchstaben",
    TEXT_GET_SUBSTRING_HELPURL: "http://publib.boulder.ibm.com/infocenter/lnxpcomp/v8v101/index.jsp?topic:%2Fcom.ibm.xlcpp8l.doc%2Flanguage%2Fref%2Farsubex.htm",
    TEXT_GET_SUBSTRING_INPUT_IN_TEXT: "in Text",
    TEXT_GET_SUBSTRING_START_FIRST: "vom ersten Buchstaben",
    TEXT_GET_SUBSTRING_START_FROM_END: "vom #ten Buchstaben von hinten",
    TEXT_GET_SUBSTRING_START_FROM_START: "vom #ten Buchstaben",
    TEXT_GET_SUBSTRING_TAIL: "",
    TEXT_GET_SUBSTRING_TOOLTIP: "Gibt den angegebenen Textabschnitt zurück.",
    TEXT_INDEXOF_HELPURL: "http://publib.boulder.ibm.com/infocenter/lnxpcomp/v8v101/index.jsp?topic:%2Fcom.ibm.xlcpp8l.doc%2Flanguage%2Fref%2Farsubex.htm",
    TEXT_INDEXOF_INPUT_INTEXT: "im Text",
    TEXT_INDEXOF_OPERATOR_FIRST: "Suche erstes Auftreten des Begriffs",
    TEXT_INDEXOF_OPERATOR_LAST: "Suche letztes Auftreten des Begriffs",
    TEXT_INDEXOF_TAIL: "",
    TEXT_INDEXOF_TOOLTIP: "Findet das erste / letzte Auftreten eines Suchbegriffs in einem Text.  Gibt die Position des Begriffs oder 0 zurück.",
    TEXT_ISEMPTY_HELPURL: "https://github.com/google/blockly/wiki/Text#checking-for-empty-text",  // untranslated
    TEXT_ISEMPTY_TITLE: "%1 ist leer?",
    TEXT_ISEMPTY_TOOLTIP: "Ist wahr (true), wenn der Text keine Zeichen enthält ist.",
    TEXT_JOIN_HELPURL: "",
    TEXT_JOIN_TITLE_CREATEWITH: "Erstelle Text aus",
    TEXT_JOIN_TOOLTIP: "Erstellt einen Text durch das Verbinden von mehreren Textelementen.",
    TEXT_LENGTH_HELPURL: "https://github.com/google/blockly/wiki/Text#text-modification",  // untranslated
    TEXT_LENGTH_TITLE: "Länge %1",
    TEXT_LENGTH_TOOLTIP: "Die Anzahl von Zeichen in einem Text. (inkl. Leerzeichen)",
    TEXT_PRINT_HELPURL: "https://github.com/google/blockly/wiki/Text#printing-text",  // untranslated
    TEXT_PRINT_TITLE: "Ausgabe %1",
    TEXT_PRINT_TOOLTIP: "Gib den Inhalt einer Variable aus.",
    TEXT_PROMPT_HELPURL: "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user",  // untranslated
    TEXT_PROMPT_TOOLTIP_NUMBER: "Fragt den Benutzer nach einer Zahl.",
    TEXT_PROMPT_TOOLTIP_TEXT: "Fragt den Benutzer nach einem Text.",
    TEXT_PROMPT_TYPE_NUMBER: "Fragt nach Zahl mit Hinweis",
    TEXT_PROMPT_TYPE_TEXT: "Fragt nach Text mit Hinweis",
    TEXT_TEXT_HELPURL: "https://de.wikipedia.org/wiki/Zeichenkette",
    TEXT_TEXT_TOOLTIP: "Ein Buchstabe, Text oder Satz.",
    TEXT_TRIM_HELPURL: "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces",  // untranslated
    TEXT_TRIM_OPERATOR_BOTH: "entferne Leerzeichen vom Anfang und vom Ende (links und rechts)",
    TEXT_TRIM_OPERATOR_LEFT: "entferne Leerzeichen vom Anfang (links)",
    TEXT_TRIM_OPERATOR_RIGHT: "entferne Leerzeichen vom Ende (rechts)",
    TEXT_TRIM_TOOLTIP: "Entfernt Leerzeichen vom Anfang und / oder Ende eines Textes.",

}