export const LOOPS = {

    CONTROLS_FLOW_STATEMENTS_HELPURL: "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks",
    CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK: "kitörni a hurokból",
    CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE: "folytassa a ciklus következő ismétlésével",
    CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK: "Szakadj ki a tartalmazó hurokból.",
    CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE: "Hagyja ki a ciklus további részét, és folytassa a következő iterációval.",
    CONTROLS_FLOW_STATEMENTS_WARNING: "Figyelmeztetés: Ez a blokk csak cikluson belül használható.",
    CONTROLS_FOREACH_HELPURL: "https://github.com/google/blockly/wiki/Loops#for-each",
    CONTROLS_FOREACH_TITLE: "a %2 listában minden egyes %1 tétel esetében",
    CONTROLS_FOREACH_TOOLTIP: "A lista minden egyes elemére állítsuk a '%1' változót az elemre, majd végezzünk el néhány utasítást.",
    CONTROLS_FOR_HELPURL: "https://github.com/google/blockly/wiki/Loops#count-with",
    CONTROLS_FOR_TITLE: "számolás %1-gyel %2-től %3-ig %4-ig",
    CONTROLS_FOR_TOOLTIP: "A '%1' változó vegye fel az értékeket a kezdőszámtól a végszámig, a megadott időközönként számolva, és végezze el a megadott blokkokat.",
    CONTROLS_REPEAT_HELPURL: "https://en.wikipedia.org/wiki/For_loop",
    CONTROLS_REPEAT_INPUT_DO: "do",
    CONTROLS_REPEAT_TITLE: "ismételje meg %1-szer",
    CONTROLS_REPEAT_TOOLTIP: "Néhány állítást többször is végezzen el.",
    CONTROLS_WHILEUNTIL_HELPURL: "https://github.com/google/blockly/wiki/Loops#repeat",
    CONTROLS_WHILEUNTIL_OPERATOR_UNTIL: "ismételjük, amíg",
    CONTROLS_WHILEUNTIL_OPERATOR_WHILE: "repeat while",
    CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL: "Amíg egy érték hamis, addig tegyen néhány utasítást.",
    CONTROLS_WHILEUNTIL_TOOLTIP_WHILE: "Amíg egy érték igaz, addig csinálj néhány utasítást.",
}