export const MATH = {

    MATH_ADDITION_SYMBOL: "+",
    MATH_ARITHMETIC_HELPURL: "https://en.wikipedia.org/wiki/Arithmetic",
    MATH_ARITHMETIC_TOOLTIP_ADD: "Return the sum of the two numbers.",
    MATH_ARITHMETIC_TOOLTIP_DIVIDE: "Return the quotient of the two numbers.",
    MATH_ARITHMETIC_TOOLTIP_MINUS: "Return the difference of the two numbers.",
    MATH_ARITHMETIC_TOOLTIP_MULTIPLY: "Return the product of the two numbers.",
    MATH_ARITHMETIC_TOOLTIP_POWER: "Return the first number raised to the power of the second number.",
    MATH_CHANGE_HELPURL: "https://en.wikipedia.org/wiki/Programming_idiom#Incrementing_a_counter",
    MATH_CHANGE_TITLE: "change %1 by %2",
    MATH_CHANGE_TOOLTIP: "Add a number to variable '%1'.",
    MATH_CONSTANT_HELPURL: "https://en.wikipedia.org/wiki/Mathematical_constant",
    MATH_CONSTANT_TOOLTIP: "Return one of the common constants: π (3.141…), e (2.718…), φ (1.618…), sqrt(2) (1.414…), sqrt(½) (0.707…), or ∞ (infinity).",
    MATH_CONSTRAIN_HELPURL: "https://en.wikipedia.org/wiki/Clamping_%28graphics%29",
    MATH_CONSTRAIN_TITLE: "constrain %1 low %2 high %3",
    MATH_CONSTRAIN_TOOLTIP: "Constrain a number to be between the specified limits (inclusive).",
    MATH_DIVISION_SYMBOL: "÷",
    MATH_IS_DIVISIBLE_BY: "is divisible by",
    MATH_IS_EVEN: "is even",
    MATH_IS_NEGATIVE: "is negative",
    MATH_IS_ODD: "is odd",
    MATH_IS_POSITIVE: "is positive",
    MATH_IS_PRIME: "is prime",
    MATH_IS_TOOLTIP: "Check if a number is an even, odd, prime, whole, positive, negative, or if it is divisible by certain number. Returns true or false.",
    MATH_IS_WHOLE: "is whole",
    MATH_MODULO_HELPURL: "https://en.wikipedia.org/wiki/Modulo_operation",
    MATH_MODULO_TITLE: "remainder of %1 ÷ %2",
    MATH_MODULO_TOOLTIP: "Return the remainder from dividing the two numbers.",
    MATH_MULTIPLICATION_SYMBOL: "×",
    MATH_NUMBER_HELPURL: "https://en.wikipedia.org/wiki/Number",
    MATH_NUMBER_TOOLTIP: "A number.",
    MATH_ONLIST_HELPURL: "",
    MATH_ONLIST_OPERATOR_AVERAGE: "average of list",
    MATH_ONLIST_OPERATOR_MAX: "max of list",
    MATH_ONLIST_OPERATOR_MEDIAN: "median of list",
    MATH_ONLIST_OPERATOR_MIN: "min of list",
    MATH_ONLIST_OPERATOR_MODE: "modes of list",
    MATH_ONLIST_OPERATOR_RANDOM: "random item of list",
    MATH_ONLIST_OPERATOR_STD_DEV: "standard deviation of list",
    MATH_ONLIST_OPERATOR_SUM: "sum of list",
    MATH_ONLIST_TOOLTIP_AVERAGE: "Return the average (arithmetic mean) of the numeric values in the list.",
    MATH_ONLIST_TOOLTIP_MAX: "Return the largest number in the list.",
    MATH_ONLIST_TOOLTIP_MEDIAN: "Return the median number in the list.",
    MATH_ONLIST_TOOLTIP_MIN: "Return the smallest number in the list.",
    MATH_ONLIST_TOOLTIP_MODE: "Return a list of the most common item(s) in the list.",
    MATH_ONLIST_TOOLTIP_RANDOM: "Return a random element from the list.",
    MATH_ONLIST_TOOLTIP_STD_DEV: "Return the standard deviation of the list.",
    MATH_ONLIST_TOOLTIP_SUM: "Return the sum of all the numbers in the list.",
    MATH_POWER_SYMBOL: "^",
    MATH_RANDOM_FLOAT_HELPURL: "https://en.wikipedia.org/wiki/Random_number_generation",
    MATH_RANDOM_FLOAT_TITLE_RANDOM: "random fraction",
    MATH_RANDOM_FLOAT_TOOLTIP: "Return a random fraction between 0.0 (inclusive) and 1.0 (exclusive).",
    MATH_RANDOM_INT_HELPURL: "https://en.wikipedia.org/wiki/Random_number_generation",
    MATH_RANDOM_INT_TITLE: "random integer from %1 to %2",
    MATH_RANDOM_INT_TOOLTIP: "Return a random integer between the two specified limits, inclusive.",
    MATH_ROUND_HELPURL: "https://en.wikipedia.org/wiki/Rounding",
    MATH_ROUND_OPERATOR_ROUND: "round",
    MATH_ROUND_OPERATOR_ROUNDDOWN: "round down",
    MATH_ROUND_OPERATOR_ROUNDUP: "round up",
    MATH_ROUND_TOOLTIP: "Round a number up or down.",
    MATH_SINGLE_HELPURL: "https://en.wikipedia.org/wiki/Square_root",
    MATH_SINGLE_OP_ABSOLUTE: "absolute",
    MATH_SINGLE_OP_ROOT: "square root",
    MATH_SINGLE_TOOLTIP_ABS: "Return the absolute value of a number.",
    MATH_SINGLE_TOOLTIP_EXP: "Return e to the power of a number.",
    MATH_SINGLE_TOOLTIP_LN: "Return the natural logarithm of a number.",
    MATH_SINGLE_TOOLTIP_LOG10: "Return the base 10 logarithm of a number.",
    MATH_SINGLE_TOOLTIP_NEG: "Return the negation of a number.",
    MATH_SINGLE_TOOLTIP_POW10: "Return 10 to the power of a number.",
    MATH_SINGLE_TOOLTIP_ROOT: "Return the square root of a number.",
    MATH_SUBTRACTION_SYMBOL: "-",
    MATH_TRIG_ACOS: "acos",
    MATH_TRIG_ASIN: "asin",
    MATH_TRIG_ATAN: "atan",
    MATH_TRIG_COS: "cos",
    MATH_TRIG_HELPURL: "https://en.wikipedia.org/wiki/Trigonometric_functions",
    MATH_TRIG_SIN: "sin",
    MATH_TRIG_TAN: "tan",
    MATH_TRIG_TOOLTIP_ACOS: "Return the arccosine of a number.",
    MATH_TRIG_TOOLTIP_ASIN: "Return the arcsine of a number.",
    MATH_TRIG_TOOLTIP_ATAN: "Return the arctangent of a number.",
    MATH_TRIG_TOOLTIP_COS: "Return the cosine of a degree (not radian).",
    MATH_TRIG_TOOLTIP_SIN: "Return the sine of a degree (not radian).",
    MATH_TRIG_TOOLTIP_TAN: "Return the tangent of a degree (not radian).",

}