export const MATH = {

    MATH_ADDITION_SYMBOL: "+",
    MATH_ARITHMETIC_HELPURL: "https://en.wikipedia.org/wiki/Arithmetic",
    MATH_ARITHMETIC_TOOLTIP_ADD: "A két szám összegét adja vissza.",
    MATH_ARITHMETIC_TOOLTIP_DIVIDE: "A két szám hányadosát adja vissza.",
    MATH_ARITHMETIC_TOOLTIP_MINUS: "A két szám különbségét adja vissza.",
    MATH_ARITHMETIC_TOOLTIP_MULTIPLY: "A két szám szorzatának visszaadása.",
    MATH_ARITHMETIC_TOOLTIP_POWER: "Visszaadja az első számot a második szám hatványára emelve.",
    MATH_CHANGE_HELPURL: "https://en.wikipedia.org/wiki/Programming_idiom#Incrementing_a_counter",
    MATH_CHANGE_TITLE: "%1 megváltoztatása %2-vel",
    MATH_CHANGE_TOOLTIP: "Egy szám hozzáadása a '%1' változóhoz.",
    MATH_CONSTANT_HELPURL: "https://en.wikipedia.org/wiki/Mathematical_constant",
    MATH_CONSTANT_TOOLTIP: "Visszaadja az általános konstansok egyikét: π (3,141...), e (2,718...), φ (1,618...), sqrt(2) (1,414...), sqrt(½) (0,707...), vagy ∞ (végtelen).",
    MATH_CONSTRAIN_HELPURL: "https://en.wikipedia.org/wiki/Clamping_%28graphics%29",
    MATH_CONSTRAIN_TITLE: "korlátozza %1 alacsony %2 magas %3",
    MATH_CONSTRAIN_TOOLTIP: "Egy számot a megadott határértékek közé szorít (beleértve).",
    MATH_DIVISION_SYMBOL: "÷",
    MATH_IS_DIVISIBLE_BY: "osztható",
    MATH_IS_EVEN: "még",
    MATH_IS_NEGATIVE: "negatív",
    MATH_IS_ODD: "páratlan",
    MATH_IS_POSITIVE: "pozitív",
    MATH_IS_PRIME: "prím",
    MATH_IS_TOOLTIP: "Ellenőrizze, hogy egy szám páros, páratlan, prím, egész, pozitív, negatív, vagy hogy osztható-e bizonyos számmal. Igaz vagy hamis értéket ad vissza.",
    MATH_IS_WHOLE: "egész",
    MATH_MODULO_HELPURL: "https://en.wikipedia.org/wiki/Modulo_operation",
    MATH_MODULO_TITLE: "%1 ÷ %2 maradéka",
    MATH_MODULO_TOOLTIP: "A két szám osztásából származó maradékot adja vissza.",
    MATH_MULTIPLICATION_SYMBOL: "×",
    MATH_NUMBER_HELPURL: "https://en.wikipedia.org/wiki/Number",
    MATH_NUMBER_TOOLTIP: "Egy szám.",
    MATH_ONLIST_HELPURL: "",
    MATH_ONLIST_OPERATOR_AVERAGE: "listák átlaga",
    MATH_ONLIST_OPERATOR_MAX: "a lista maximuma",
    MATH_ONLIST_OPERATOR_MEDIAN: "a lista mediánja",
    MATH_ONLIST_OPERATOR_MIN: "a lista min értéke",
    MATH_ONLIST_OPERATOR_MODE: "a lista módjai",
    MATH_ONLIST_OPERATOR_RANDOM: "a lista véletlenszerű eleme",
    MATH_ONLIST_OPERATOR_STD_DEV: "a lista szórása",
    MATH_ONLIST_OPERATOR_SUM: "a lista összege",
    MATH_ONLIST_TOOLTIP_AVERAGE: "A lista numerikus értékeinek átlagát (számtani átlagát) adja vissza.",
    MATH_ONLIST_TOOLTIP_MAX: "A lista legnagyobb számának visszaadása.",
    MATH_ONLIST_TOOLTIP_MEDIAN: "A listában szereplő számok mediánjának visszaadása.",
    MATH_ONLIST_TOOLTIP_MIN: "A lista legkisebb számának visszaadása.",
    MATH_ONLIST_TOOLTIP_MODE: "A listában található leggyakoribb elem(ek) visszaadása.",
    MATH_ONLIST_TOOLTIP_RANDOM: "Egy véletlenszerű elem visszaadása a listából.",
    MATH_ONLIST_TOOLTIP_STD_DEV: "A lista szórásának visszaadása.",
    MATH_ONLIST_TOOLTIP_SUM: "A lista összes számának összegét adja vissza.",
    MATH_POWER_SYMBOL: "^",
    MATH_RANDOM_FLOAT_HELPURL: "https://en.wikipedia.org/wiki/Random_number_generation",
    MATH_RANDOM_FLOAT_TITLE_RANDOM: "véletlen tört",
    MATH_RANDOM_FLOAT_TOOLTIP: "0,0 (beleértve) és 1,0 (kizárólag) közötti véletlen tört visszaadása.",
    MATH_RANDOM_INT_HELPURL: "https://en.wikipedia.org/wiki/Random_number_generation",
    MATH_RANDOM_INT_TITLE: "véletlen egész szám %1 és %2 között",
    MATH_RANDOM_INT_TOOLTIP: "A két megadott határérték közötti véletlen egész számot ad vissza, beleértve.",
    MATH_ROUND_HELPURL: "https://en.wikipedia.org/wiki/Rounding",
    MATH_ROUND_OPERATOR_ROUND: "round",
    MATH_ROUND_OPERATOR_ROUNDDOWN: "lefelé kerekítés",
    MATH_ROUND_OPERATOR_ROUNDUP: "felfelé kerekítés",
    MATH_ROUND_TOOLTIP: "Egy szám felfelé vagy lefelé kerekítése.",
    MATH_SINGLE_HELPURL: "https://en.wikipedia.org/wiki/Square_root",
    MATH_SINGLE_OP_ABSOLUTE: "abszolút",
    MATH_SINGLE_OP_ROOT: "négyzetgyök",
    MATH_SINGLE_TOOLTIP_ABS: "Egy szám abszolút értékének visszaadása.",
    MATH_SINGLE_TOOLTIP_EXP: "Visszaadja e értékét egy szám hatványára.",
    MATH_SINGLE_TOOLTIP_LN: "Egy szám természetes logaritmusának visszaadása.",
    MATH_SINGLE_TOOLTIP_LOG10: "Egy szám 10-es bázisú logaritmusának visszaadása.",
    MATH_SINGLE_TOOLTIP_NEG: "Egy szám negációja.",
    MATH_SINGLE_TOOLTIP_POW10: "Egy szám 10-es hatványának visszaadása.",
    MATH_SINGLE_TOOLTIP_ROOT: "Egy szám négyzetgyökének visszaadása.",
    MATH_SUBTRACTION_SYMBOL: "-",
    MATH_TRIG_ACOS: "acos",
    MATH_TRIG_ASIN: "asin",
    MATH_TRIG_ATAN: "atan",
    MATH_TRIG_COS: "cos",
    MATH_TRIG_HELPURL: "https://en.wikipedia.org/wiki/Trigonometric_functions",
    MATH_TRIG_SIN: "sin",
    MATH_TRIG_TAN: "tan",
    MATH_TRIG_TOOLTIP_ACOS: "Egy szám arccosinusának visszaadása.",
    MATH_TRIG_TOOLTIP_ASIN: "Egy szám ívszinuszának visszaadása.",
    MATH_TRIG_TOOLTIP_ATAN: "Egy szám arctangensének visszaadása.",
    MATH_TRIG_TOOLTIP_COS: "Egy fok (nem radián) koszinuszának visszaadása.",
    MATH_TRIG_TOOLTIP_SIN: "Egy fok (nem radián) szinuszának visszaadása.",
    MATH_TRIG_TOOLTIP_TAN: "Egy fok (nem radián) érintőjének visszaadása.",

}