export const TEXT = {

    TEXT_APPEND_APPENDTEXT: "append text",
    TEXT_APPEND_HELPURL: "https://github.com/google/blockly/wiki/Text#text-modification",
    TEXT_APPEND_TO: "to",
    TEXT_APPEND_TOOLTIP: "Append some text to variable '%1'.",
    TEXT_CHANGECASE_HELPURL: "https://github.com/google/blockly/wiki/Text#adjusting-text-case",
    TEXT_CHANGECASE_OPERATOR_LOWERCASE: "to lower case",
    TEXT_CHANGECASE_OPERATOR_TITLECASE: "to Title Case",
    TEXT_CHANGECASE_OPERATOR_UPPERCASE: "to UPPER CASE",
    TEXT_CHANGECASE_TOOLTIP: "Return a copy of the text in a different case.",
    TEXT_CHARAT_FIRST: "get first letter",
    TEXT_CHARAT_FROM_END: "get letter # from end",
    TEXT_CHARAT_FROM_START: "get letter #",
    TEXT_CHARAT_HELPURL: "https://github.com/google/blockly/wiki/Text#extracting-text",
    TEXT_CHARAT_INPUT_INTEXT: "in text",
    TEXT_CHARAT_LAST: "get last letter",
    TEXT_CHARAT_RANDOM: "get random letter",
    TEXT_CHARAT_TAIL: "",
    TEXT_CHARAT_TOOLTIP: "Returns the letter at the specified position.",
    TEXT_CREATE_JOIN_ITEM_TOOLTIP: "Add an item to the text.",
    TEXT_CREATE_JOIN_TITLE_JOIN: "join",
    TEXT_CREATE_JOIN_TOOLTIP: "Add, remove, or reorder sections to reconfigure this text block.",
    TEXT_GET_SUBSTRING_END_FROM_END: "to letter # from end",
    TEXT_GET_SUBSTRING_END_FROM_START: "to letter #",
    TEXT_GET_SUBSTRING_END_LAST: "to last letter",
    TEXT_GET_SUBSTRING_HELPURL: "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text",
    TEXT_GET_SUBSTRING_INPUT_IN_TEXT: "in text",
    TEXT_GET_SUBSTRING_START_FIRST: "get substring from first letter",
    TEXT_GET_SUBSTRING_START_FROM_END: "get substring from letter # from end",
    TEXT_GET_SUBSTRING_START_FROM_START: "get substring from letter #",
    TEXT_GET_SUBSTRING_TAIL: "",
    TEXT_GET_SUBSTRING_TOOLTIP: "Returns a specified portion of the text.",
    TEXT_INDEXOF_HELPURL: "https://github.com/google/blockly/wiki/Text#finding-text",
    TEXT_INDEXOF_INPUT_INTEXT: "in text",
    TEXT_INDEXOF_OPERATOR_FIRST: "find first occurrence of text",
    TEXT_INDEXOF_OPERATOR_LAST: "find last occurrence of text",
    TEXT_INDEXOF_TAIL: "",
    TEXT_INDEXOF_TOOLTIP: "Returns the index of the first/last occurrence of the first text in the second text. Returns 0 if text is not found.",
    TEXT_ISEMPTY_HELPURL: "https://github.com/google/blockly/wiki/Text#checking-for-empty-text",
    TEXT_ISEMPTY_TITLE: "%1 is empty",
    TEXT_ISEMPTY_TOOLTIP: "Returns true if the provided text is empty.",
    TEXT_JOIN_HELPURL: "https://github.com/google/blockly/wiki/Text#text-creation",
    TEXT_JOIN_TITLE_CREATEWITH: "create text with",
    TEXT_JOIN_TOOLTIP: "Create a piece of text by joining together any number of items.",
    TEXT_LENGTH_HELPURL: "https://github.com/google/blockly/wiki/Text#text-modification",
    TEXT_LENGTH_TITLE: "length of %1",
    TEXT_LENGTH_TOOLTIP: "Returns the number of letters (including spaces) in the provided text.",
    TEXT_PRINT_HELPURL: "https://github.com/google/blockly/wiki/Text#printing-text",
    TEXT_PRINT_TITLE: "print %1",
    TEXT_PRINT_TOOLTIP: "Print the specified text, number or other value.",
    TEXT_PROMPT_HELPURL: "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user",
    TEXT_PROMPT_TOOLTIP_NUMBER: "Prompt for user for a number.",
    TEXT_PROMPT_TOOLTIP_TEXT: "Prompt for user for some text.",
    TEXT_PROMPT_TYPE_NUMBER: "prompt for number with message",
    TEXT_PROMPT_TYPE_TEXT: "prompt for text with message",
    TEXT_TEXT_HELPURL: "https://en.wikipedia.org/wiki/String_(computer_science)",
    TEXT_TEXT_TOOLTIP: "A letter, word, or line of text.",
    TEXT_TRIM_HELPURL: "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces",
    TEXT_TRIM_OPERATOR_BOTH: "trim spaces from both sides of",
    TEXT_TRIM_OPERATOR_LEFT: "trim spaces from left side of",
    TEXT_TRIM_OPERATOR_RIGHT: "trim spaces from right side of",
    TEXT_TRIM_TOOLTIP: "Return a copy of the text with spaces removed from one or both ends.",
}