export const TEXT = {

    TEXT_APPEND_APPENDTEXT: "szöveg hozzáadása",
    TEXT_APPEND_HELPURL: "https://github.com/google/blockly/wiki/Text#text-modification",
    TEXT_APPEND_TO: "to",
    TEXT_APPEND_TOOLTIP: "Append some text to variable '%1'.",
    TEXT_CHANGECASE_HELPURL: "https://github.com/google/blockly/wiki/Text#adjusting-text-case",
    TEXT_CHANGECASE_OPERATOR_LOWERCASE: "kisbetűre",
    TEXT_CHANGECASE_OPERATOR_TITLECASE: "a cím nagybetűre",
    TEXT_CHANGECASE_OPERATOR_UPPERCASE: "to UPPER CASE",
    TEXT_CHANGECASE_TOOLTIP: "A szöveg másolatának visszaadása más nagybetűvel.",
    TEXT_CHARAT_FIRST: "első betű kinyerése",
    TEXT_CHARAT_FROM_END: "get letter # from end",
    TEXT_CHARAT_FROM_START: "get letter #",
    TEXT_CHARAT_HELPURL: "https://github.com/google/blockly/wiki/Text#extracting-text",
    TEXT_CHARAT_INPUT_INTEXT: "szövegben",
    TEXT_CHARAT_LAST: "utolsó betű lekérdezése",
    TEXT_CHARAT_RANDOM: "véletlenszerűen kiválasztott betű",
    TEXT_CHARAT_TAIL: "",
    TEXT_CHARAT_TOOLTIP: "A megadott pozícióban lévő betűt adja vissza.",
    TEXT_CREATE_JOIN_ITEM_TOOLTIP: "Egy elem hozzáadása a szöveghez.",
    TEXT_CREATE_JOIN_TITLE_JOIN: "join",
    TEXT_CREATE_JOIN_TOOLTIP: "A szövegblokk újrakonfigurálásához szakaszok hozzáadása, eltávolítása vagy átrendezése.",
    TEXT_GET_SUBSTRING_END_FROM_END: "a végétől # betűig",
    TEXT_GET_SUBSTRING_END_FROM_START: "# betűig",
    TEXT_GET_SUBSTRING_END_LAST: "az utolsó betűig",
    TEXT_GET_SUBSTRING_HELPURL: "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text",
    TEXT_GET_SUBSTRING_INPUT_IN_TEXT: "szövegben",
    TEXT_GET_SUBSTRING_START_FIRST: "az első betűtől kezdődően részláncot kap",
    TEXT_GET_SUBSTRING_START_FROM_END: "get substring from letter # from end",
    TEXT_GET_SUBSTRING_START_FROM_START: "a # betűből származó részlánc kinyerése",
    TEXT_GET_SUBSTRING_TAIL: "",
    TEXT_GET_SUBSTRING_TOOLTIP: "A szöveg egy megadott részét adja vissza.",
    TEXT_INDEXOF_HELPURL: "https://github.com/google/blockly/wiki/Text#finding-text",
    TEXT_INDEXOF_INPUT_INTEXT: "a szövegben",
    TEXT_INDEXOF_OPERATOR_FIRST: "a szöveg első előfordulásának keresése",
    TEXT_INDEXOF_OPERATOR_LAST: "a szöveg utolsó előfordulásának keresése",
    TEXT_INDEXOF_TAIL: "",
    TEXT_INDEXOF_TOOLTIP: "Az első szöveg első/utolsó előfordulásának indexét adja vissza a második szövegben. 0-t ad vissza, ha a szöveg nem található.",
    TEXT_ISEMPTY_HELPURL: "https://github.com/google/blockly/wiki/Text#checking-for-empty-text",
    TEXT_ISEMPTY_TITLE: "%1 üres",
    TEXT_ISEMPTY_TOOLTIP: "Igazat ad vissza, ha a megadott szöveg üres.",
    TEXT_JOIN_HELPURL: "https://github.com/google/blockly/wiki/Text#text-creation",
    TEXT_JOIN_TITLE_CREATEWITH: "create text with",
    TEXT_JOIN_TOOLTIP: "Egy szövegdarab létrehozása tetszőleges számú elem összekapcsolásával.",
    TEXT_LENGTH_HELPURL: "https://github.com/google/blockly/wiki/Text#text-modification",
    TEXT_LENGTH_TITLE: "hossza %1",
    TEXT_LENGTH_TOOLTIP: "Visszaadja a megadott szöveg betűinek számát (szóközökkel együtt).",
    TEXT_PRINT_HELPURL: "https://github.com/google/blockly/wiki/Text#printing-text",
    TEXT_PRINT_TITLE: "print %1",
    TEXT_PRINT_TOOLTIP: "A megadott szöveg, szám vagy egyéb érték nyomtatása.",
    TEXT_PROMPT_HELPURL: "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user",
    TEXT_PROMPT_TOOLTIP_NUMBER: "A felhasználó szám megadására való felszólítás.",
    TEXT_PROMPT_TOOLTIP_TEXT: "Prompt for user for some text.",
    TEXT_PROMPT_TYPE_NUMBER: "számonkérés üzenettel",
    TEXT_PROMPT_TYPE_TEXT: "prompt for text with message",
    TEXT_TEXT_HELPURL: "https://en.wikipedia.org/wiki/String_(computer_science)",
    TEXT_TEXT_TOOLTIP: "Egy betű, szó vagy egy sor szöveg.",
    TEXT_TRIM_HELPURL: "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces",
    TEXT_TRIM_OPERATOR_BOTH: "trim space from both sides of",
    TEXT_TRIM_OPERATOR_LEFT: "trim space from left side of",
    TEXT_TRIM_OPERATOR_RIGHT: "trim spaces from right side of",
    TEXT_TRIM_TOOLTIP: "A szöveg másolatának visszaadása az egyik vagy mindkét végéről eltávolított szóközökkel.",
}