export const LOGIC = {

    CONTROLS_IF_ELSEIF_TOOLTIP: "Add a condition to the if block.",
    CONTROLS_IF_ELSE_TOOLTIP: "Add a final, catch-all condition to the if block.",
    CONTROLS_IF_HELPURL: "https://github.com/google/blockly/wiki/IfElse",
    CONTROLS_IF_IF_TOOLTIP: "Add, remove, or reorder sections to reconfigure this if block.",
    CONTROLS_IF_MSG_ELSE: "else",
    CONTROLS_IF_MSG_ELSEIF: "else if",
    CONTROLS_IF_MSG_IF: "if",
    CONTROLS_IF_TOOLTIP_1: "If a value is true, then do some statements.",
    CONTROLS_IF_TOOLTIP_2: "If a value is true, then do the first block of statements. Otherwise, do the second block of statements.",
    CONTROLS_IF_TOOLTIP_3: "If the first value is true, then do the first block of statements. Otherwise, if the second value is true, do the second block of statements.",
    CONTROLS_IF_TOOLTIP_4: "If the first value is true, then do the first block of statements. Otherwise, if the second value is true, do the second block of statements. If none of the values are true, do the last block of statements.",
    LOGIC_BOOLEAN_FALSE: "false",
    LOGIC_BOOLEAN_HELPURL: "https://github.com/google/blockly/wiki/Logic#values",
    LOGIC_BOOLEAN_TOOLTIP: "Returns either true or false.",
    LOGIC_BOOLEAN_TRUE: "true",
    LOGIC_COMPARE_HELPURL: "https://en.wikipedia.org/wiki/Inequality_(mathematics)",
    LOGIC_COMPARE_TOOLTIP_EQ: "Return true if both inputs equal each other.",
    LOGIC_COMPARE_TOOLTIP_GT: "Return true if the first input is greater than the second input.",
    LOGIC_COMPARE_TOOLTIP_GTE: "Return true if the first input is greater than or equal to the second input.",
    LOGIC_COMPARE_TOOLTIP_LT: "Return true if the first input is smaller than the second input.",
    LOGIC_COMPARE_TOOLTIP_LTE: "Return true if the first input is smaller than or equal to the second input.",
    LOGIC_COMPARE_TOOLTIP_NEQ: "Return true if both inputs are not equal to each other.",
    LOGIC_NEGATE_HELPURL: "https://github.com/google/blockly/wiki/Logic#not",
    LOGIC_NEGATE_TITLE: "not %1",
    LOGIC_NEGATE_TOOLTIP: "Returns true if the input is false. Returns false if the input is true.",
    LOGIC_NULL: "null",
    LOGIC_NULL_HELPURL: "https://en.wikipedia.org/wiki/Nullable_type",
    LOGIC_NULL_TOOLTIP: "Returns null.",
    LOGIC_OPERATION_AND: "and",
    LOGIC_OPERATION_HELPURL: "https://github.com/google/blockly/wiki/Logic#logical-operations",
    LOGIC_OPERATION_OR: "or",
    LOGIC_OPERATION_TOOLTIP_AND: "Return true if both inputs are true.",
    LOGIC_OPERATION_TOOLTIP_OR: "Return true if at least one of the inputs is true.",
    LOGIC_TERNARY_CONDITION: "test",
    LOGIC_TERNARY_HELPURL: "https://en.wikipedia.org/wiki/%3F:",
    LOGIC_TERNARY_IF_FALSE: "if false",
    LOGIC_TERNARY_IF_TRUE: "if true",
    LOGIC_TERNARY_TOOLTIP: "Check the condition in 'test'. If the condition is true, returns the 'if true' value, otherwise returns the 'if false' value.",


    cases_add: "Case",
    cases_condition: "Case (Variable) : ",
    cases_do: "Do",
    cases_switch: "Variable",
    cases_tooltip: "Does something if the condition is true. If there isn't a matching case the default function will be executed.",

}