name: Cypress Tests

on:
  push:
    branches: [main, development]
    tags: ["v*.*.*"]
  pull_request:
    branches:
      - main
      - development
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npx --yes serve -s build -l 3000

      - name: Run CTRF report
        if: always()
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: "./ctrf/*.json"
          summary: true
          pull-request: true
          pull-request-report: true
          comment-tag: cypress-tests
          on-fail-only: true
          test-report: false
          annotate: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
